services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MacGyer\MgImageComparisonSlider\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model*'
